#In this compose file we use exixting volume and exixting network
version: "3.0"
services: 
    springbootapp:
        image: redbull200/springboot-mongo:IMAGEVERSION
        ports: 
            - 8080:8080
        environment: 
            - MONGO_DB_HOSTNAME=mongodb
            - MONGO_DB_USERNAME=devdb
            - MONGO_DB_PASSWORD=devdb@123
        networks: 
            - mybridge
    mongodb:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=devdb
            - MONGO_INITDB_ROOT_PASSWORD=devdb@123
        networks: 
            - mybridge
        volumes: 
            - mongodbvolume:/data/db
volumes: 
    mongodbvolume:
        external: true
networks: 
    mybridge:
        external: true
